export const INDONESIA_PROVINCES = [
  "DKI Jakarta",
  "Jawa Barat",
  "Jawa Tengah",
  "Jawa Timur",
  "Banten",
  "D.I. Yogyakarta",
  "Bali",
  "Sumatera Utara",
  "Sumatera Barat",
  "Sumatera Selatan",
  "Riau",
  "Kepulauan Riau",
  "Lampung",
  "Sulawesi Selatan",
  "Sulawesi Utara",
  "Kalimantan Timur",
  "Kalimantan Barat",
  "Nusa Tenggara Barat",
  "Papua",
];

export const INDONESIA_CITIES = {
  "DKI Jakarta": ["Jakarta Selatan", "Jakarta Pusat", "Jakarta Barat", "Jakarta Timur", "Jakarta Utara", "Kepulauan Seribu"],
  "Jawa Barat": ["Kota Bandung", "Kab. Bandung", "Kota Bekasi", "Kab. Bekasi", "Kota Depok", "Kota Bogor", "Kab. Bogor", "Kota Cimahi", "Kota Tasikmalaya", "Kab. Karawang", "Kab. Cirebon"],
  "Jawa Tengah": ["Kota Semarang", "Kota Surakarta (Solo)", "Kota Magelang", "Kota Tegal", "Kab. Banyumas (Purwokerto)", "Kab. Kudus", "Kab. Cilacap"],
  "Jawa Timur": ["Kota Surabaya", "Kota Malang", "Kota Kediri", "Kota Sidoarjo", "Kab. Jember", "Kota Banyuwangi", "Kota Madiun", "Kota Batu"],
  "Banten": ["Kota Tangerang", "Kota Tangerang Selatan", "Kota Serang", "Kota Cilegon", "Kab. Tangerang"],
  "D.I. Yogyakarta": ["Kota Yogyakarta", "Kab. Sleman", "Kab. Bantul", "Kab. Gunungkidul", "Kab. Kulon Progo"],
  "Bali": ["Kota Denpasar", "Kab. Badung", "Kab. Gianyar", "Kab. Tabanan", "Kab. Buleleng"],
  "Sumatera Utara": ["Kota Medan", "Kota Binjai", "Kota Pematangsiantar", "Kab. Deli Serdang"],
  "Sumatera Barat": ["Kota Padang", "Kota Bukittinggi", "Kota Payakumbuh"],
  "Sumatera Selatan": ["Kota Palembang", "Kota Prabumulih", "Kab. Muara Enim"],
  "Riau": ["Kota Pekanbaru", "Kota Dumai", "Kab. Kampar"],
  "Kepulauan Riau": ["Kota Batam", "Kota Tanjungpinang"],
  "Lampung": ["Kota Bandar Lampung", "Kota Metro"],
  "Sulawesi Selatan": ["Kota Makassar", "Kota Parepare", "Kab. Gowa"],
  "Sulawesi Utara": ["Kota Manado", "Kota Bitung"],
  "Kalimantan Timur": ["Kota Samarinda", "Kota Balikpapan", "Kota Bontang"],
  "Kalimantan Barat": ["Kota Pontianak", "Kota Singkawang"],
  "Nusa Tenggara Barat": ["Kota Mataram", "Kab. Lombok Barat"],
  "Papua": ["Kota Jayapura", "Kab. Jayapura"],
};
